# Generated by Django 2.2.5 on 2020-04-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaintapp', '0002_auto_20200421_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='WardenInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media')),
            ],
        ),
    ]
