# Generated by Django 2.2.5 on 2020-04-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaintapp', '0003_wardeninfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardeninfo',
            name='designation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wardeninfo',
            name='warden_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
