# Generated by Django 2.2.5 on 2020-04-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaintapp', '0004_auto_20200422_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintinfo',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
