# Generated by Django 2.2.5 on 2020-07-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaintapp', '0006_auto_20200727_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintinfo',
            name='block',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
