# Generated by Django 2.2.5 on 2020-07-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaintapp', '0007_complaintinfo_block'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaintinfo',
            old_name='enrollment_num',
            new_name='room_no',
        ),
        migrations.RemoveField(
            model_name='complaintinfo',
            name='room_num',
        ),
        migrations.AddField(
            model_name='complaintinfo',
            name='reg_no',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
